apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hkg6rtebt-go
  janus-idp.io/tekton: hkg6rtebt-go
  backstage.io/kubernetes-id: hkg6rtebt-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: hkg6rtebt-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
