apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hkg6rtebt-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hkg6rtebt-go 
  name: hkg6rtebt-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hkg6rtebt-go 
